language: rust
rust:
  - stable
sudo: false
git:
    submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
    - export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/sdk/bin/linux_centos7
script:
  - cargo build
  - cargo test
env:
  global:
    - RUST_LOG=xtp=trace