[package]
name = "xtp"
version = "0.1.0"
authors = ["Weiyuan Wu <doomsplayer@gmail.com>"]
edition = "2018"

[dependencies]
xtp-sys = { path = "../xtp-sys" }
libc = "0.2"

[lib]
name = "xtp"
path = "src/lib.rs"
